<?php
/*
* Name Extension: Cmsmart megamenu
* Author: The Cmsmart Development Team 
* Date Created: 06/09/2013
* Websites: http://cmsmart.net
* Technical Support: Forum - http://cmsmart.net/support
* GNU General Public License v3 (http://opensource.org/licenses/GPL-3.0)
* Copyright © 2011-2013 Cmsmart.net. All Rights Reserved.
*/
?>
<?php
/**
 * Top menu for store
 *
 * @see Mage_Catalog_Block_Navigation
 */
?>
<?php
/**
 * $this->renderCategoriesMenuHtml() supports optional arguments:
 * bool Add opener if menu is used as accordion
 * int Level number for list item class to start from
 * string Extra class of outermost list items
 * string If specified wraps children list in div with this class
 */
?>
<?php $_menu = $this->renderCategoriesMenuHtml(FALSE, 0,'level-top'); ?>

<?php
	$theme = $this->helper('megamenu');

?>
<div class="nav-container h-100">
    <div class="container">
        <div class="row">
            <div class="col-xs-3">
                <div class="header-social-area">
                    <a href="#"><span class="karl-level">Share</span> <i class="fa fa-pinterest" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
                    <a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="col-xs-6">
	            <!-- <div class="nav" style="width: <?php // echo $theme->getCfg('mainmenu/width_menu').'px' ?>;"> -->
                <div class="nav navbar navbar-expand-lg align-items-start">
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#karl-navbar" aria-controls="karl-navbar" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"><i class="ti-menu"></i></span></button>
                    <div class="collapse navbar-collapse align-items-start collapse" id="karl-navbar">
                        <ul id="nav" class="grid-full navbar-nav animated">
                            <?php //Display "Home" link, if enabled ?>
                            <?php if ($theme->getCfg('mainmenu/home')): ?>
                                <li id="nav-home-link" class="nav-item level <?php if (Mage::helper('core/url')->getCurrentUrl() === Mage::helper('core/url')->getHomeUrl()):?> active<?php endif;?>">
                                    <?php if ($theme->getCfg('mainmenu/home_img')): ?>
                                        <a class="nav-link home-img " href="<?php echo $this->getBaseUrl(); ?>"><?php echo $this->__('Home'); ?></a>
                                    <?php else: ?>
                                        <a class="nav-link" style="background-color:<?php echo $theme->getCfg('mainmenu/home_background'); ?>;" href="<?php echo $this->getBaseUrl(); ?>"><span style="color:<?php echo $theme->getCfg('mainmenu/home_color'); ?>;"><?php echo $this->__('Home'); ?></span></a>
                                    <?php endif; ?>
                                </li>
                            <?php endif; ?>
                            <?php echo $_menu;?>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-xs-3">
                <div class="help-line">
                    <?php $phone =  Mage::getStoreConfig('general/store_information/phone')?>
                    <a href="tel:<?php echo str_replace(" ","",$phone);?>"><i class="ti-headphone-alt"></i> <?php echo $phone;?></a>
                </div>
            </div>
        </div>
	</div>
</div> <!-- end: nav-container -->
<section class="top-discount-area d-md-flex align-items-center">
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5>Free Shipping &amp; Returns</h5>
        <h6><a href="#">BUY NOW</a></h6>
    </div>
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5>20% Discount for all dresses</h5>
        <h6>USE CODE: Colorlib</h6>
    </div>
    <!-- Single Discount Area -->
    <div class="single-discount-area">
        <h5>20% Discount for students</h5>
        <h6>USE CODE: Colorlib</h6>
    </div>
</section>